CREATE SCHEMA LAB2;
CREATE TABLE EMP_1 

(EMP_NUM CHAR(3),
EMP_LNAME VARCHAR(15),
EMP_FNAME VARCHAR(15),
EMP_INITIAL CHAR(1),
EMP_HIREDATE DATE,
JOB_CODE CHAR(3));

INSERT INTO EMP_1(EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE)
VALUES ('1', 'VICENTE', 'LORRAINE', 'G', '2023-04-13', '501');
INSERT INTO EMP_1(EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE)
VALUES ('2', 'JAO', 'JESUS', 'B', '2023-04-13', '502');

SELECT * FROM LAB2.EMP_1
WHERE JOB_CODE = '502';

